export class counttask_md {
    orgcode: string;
    site: string;
    depot: string;
    spcarea: string;
    counttype: string;
    countcode: string;
    countname: string;
    datestart: Date | string | null;
    dateend: Date | string | null;
    isblock: number;
    remarks: string;
    tflow: string;
    datecreate: Date | string | null;
    accncreate: string;
    datemodify: Date | string | null;
    accnmodify: string;
    procmodify: string;
}

export class countplan_md {
    orgcode: string;
    site: string;
    depot: string;
    spcarea: string;
    countcode: string;
    plancode: string;
    planname: string;
    accnassign: string;
    accnwork: string;
    szone: string;
    ezone: string;
    saisle: string;
    eaisle: string;
    sbay: string;
    ebay: string;
    slevel: string;
    elevel: string;
    isroaming: number;
    isblock: number;
    isdatemfg: number;
    isdatexp: number;
    isbatchno: number;
    isserialno: number;
    allowscanhu: number;
    tflow: string;
    cntpercentage: number;
    cnterror: number;
    cntlines: number;
    cntactual: number;
    cnttime: string;
    datestart: Date | string | null;
    pctstart: number;
    datevld: Date | string | null;
    pctvld: number;
    accnvld: string;
    devicevld: string;
    remarksvld: string;
    datecreate: Date | string | null;
    accncreate: string;
    datemodify: Date | string | null;
    accnmodify: string;
    procmodify: string;
    isoddeven: number;
    planorigin: string;
}

export class countline_md {
    orgcode: string;
    site: string;
    depot: string;
    spcarea: string;
    countcode: string;
    plancode: string;
    loccode: string;
    locseq: number;
    unitcount: string;
    stbarcode: string;
    starticle: string;
    stpv: number;
    stlv: number;
    stqtysku: number;
    stqtypu: number;
    stlotmfg: string;
    stdatemfg: Date;
    stdateexp: Date;
    stserialno: string;
    sthuno: string;
    cnbarcode: string;
    cnarticle: string;
    cnpv: number;
    cnlv: number;
    cnqtysku: number;
    cnqtypu: number;
    cnlotmfg: string;
    cndatemfg: Date;
    cndateexp: Date;
    cnserialno: string;
    cnhuno: string;
    cnflow: string;
    cnmsg: string;
    isskip: number;
    isrgen: number;
    iswrgln: number;
    countdevice: string;
    countdate: Date | string | null;
    corcode: string;
    corqty: number;
    coraccn: string;
    cordevice: string;
    cordate: Date | string | null;
    tflow: string;
    datecreate: Date | string | null;
    accncreate: string;
    datemodify: Date | string | null;
    accnmodify: string;
    procmodify: string;
    productdesc: string;
    locctype: string;
}
export interface countcorrection_md {
    orgcode?: string;
    site?: string;
    depot?: string;
    counttype?: string;
    countcode?: string;
    countname?: string;
    barcode?: string;
    article?: string;
    pv?: number;
    lv?: number;
    description?: string;
    corcode?: string;
    corqty?: number;
    corsku?: number;
    unitcount?: string;
    skuofpck?: number;
    skuweight?: number;
    skuvolume?: number;
    unitmanage?: number;
    unitprep?: number;
    taskstate?: string;
}
export class confirmline_md {
    orgcode: string;
    site: string;
    depot: string;
    spcarea: string;
    counttype: string;
    countcode: string;
    countname: string;
    datestart: string | null;
    dateend: string | null;
    plancode: string;
    loccode: string;
    huno: string;
    pctvld: number;
    locseq: number;
    unitcount: string;
    barcode: string;
    article: string;
    pv: number;
    lv: number;
    description: string;
    stqtysku: number;
    stqtypu: number;
    cnqtypu: number;
    corcode: string;
    corqty: number;
    skuofpck: number;
    skuweight: number;
    skuvolume: number;
    taskstate: string;
}

export interface createhu_md {
    orgcode?: string;
    site?: string;
    depot?: string;
    loccode?: string;
    article?: string;
    pv?: string;
    lv?: string;
    qtypu?: number;
    qtyunit?: string;
    countcode?: string;
    plancode?: string;
    accncode?: string;
    remarks?: string;
    mergeno?: string;
    huno?: string;
}

export interface product_vld {
    orgcode?: string;
    site?: string;
    depot?: string;
    barcode?: string;
    article?: string;
    pv?: number;
    lv?: number;
    descalt?: string;
    skuweight?: number;
    skuvolume?: number;
    unitmanage?: string;
    loccode?: string;
    locarea?: string;
    loctype?: string;
    locunit?: string;
    huno?: string;
    unitcount?: string;
    unitdestr?: string;
    skuofunit?: number;
    countcode?: string;
    plancode?: string;
    linecode?: number;
    qtycount?: number;
    accncode?: string;
    isnewhu?: boolean;
    lotmfg?: string;
    datemfg?: Date;
    dateexp?: Date;
    serialno?: string;
    rtoskuofpu?: number;
    rtopckoflayer?: number;
    rtolayerofhu?: number;
    rtopckofpallet?: number;
    rtoskuofipck?: number;
    rtoskuofpck?: number;
    rtoskuoflayer?: number;
    rtoskuofhu?: number;
}