import { NumberValueAccessor } from '@angular/forms';

export class product_ls {
    orgcode: string;
    site: string; 
    depot: string; 
    spcarea: string; 
    article: string; 
    articletype: string; 
    pv: number; 
    lv: number; 
    descalt: string; 
    thcode: string; 
    tflow: string; 
    cronhand: number;
    cronblock: number; 
    crincmng: number; 
    croudeliv: number;
}
export class product_pm extends product_ls { 
    description: string; 
    hdivison: string; 
    hdepartment: string; 
    hsubdepart: string; 
    hclass: string; 
    hsubclass: string; 
    typemanage: string; 
    searchall: string;
    ismeasurement:string;
}
export class product_ix extends product_ls { 
    description: string; 
    dlcall: number; 
    dlcfactory: number; 
    dlcwarehouse: number; 
    dlcshop: number; 
    dlconsumer: number; 
    hdivison: string; 
    hdepartment: string; 
    hsubdepart: string; 
    hclass: string; 
    hsubclass: string; 
    typemanage: string; 
    unitmanage: string; 
    unitreceipt: string; 
    unitprep: string; 
    unitsale: string; 
    unitstock: string; 
    unitweight: string; 
    unitdimension: string; 
    unitvolume: string; 
    hucode: string; 
    skulength: number; 
    skuwidth: number; 
    skuheight: number; 
    skugrossweight: number; 
    skuweight: number; 
    skuvolume: number; 
    rtoskuofpu: number; 
    rtoskuofipck: number; 
    rtoskuofpck: number; 
    rtoskuoflayer: number; 
    rtoskuofhu: number; 
    innaturalloss: number; 
    ounaturalloss: number; 
    costavg: number; 
    pulength: number; 
    puwidth: number; 
    puheight: number; 
    pugrossweight: number; 
    puweight: number; 
    puvolume: number; 
    ipcklength: number; 
    ipckwidth: number; 
    ipckheight: number; 
    ipckgrossweight: number; 
    ipckweight: number; 
    ipckvolume: number; 
    pcklength: number; 
    pckwidth: number; 
    pckheight: number; 
    pckgrossweight: number; 
    pckweight: number; 
    pckvolume: number; 
    layerlength: number; 
    layerwidth: number; 
    layerheight: number; 
    layergrossweight: number; 
    layerweight: number; 
    layervolume: number; 
    hulength: number; 
    huwidth: number; 
    huheight: number; 
    hugrossweight: number; 
    huweight: number; 
    huvolume: number; 
    tempmin: number; 
    tempmax: number; 
    fileid: string; 
    rowops: string; 
    ermsg: string; 
    dateops: Date | string | null; 
}

export class product_md extends product_ls { 
    orgcode : string; 
    site : string; 
    depot : string; 
    spcarea : string; 
    article : string; 
    articletype : string; 
    pv : number; 
    lv : number; 
    description : string; 
    descalt : string; 
    thcode : string; 
    dlcall : number; 
    dlcfactory : number; 
    dlcwarehouse : number; 
    dlcshop : number; 
    dlconsumer : number; 
    hdivison : string; 
    hdepartment : string; 
    hsubdepart : string; 
    hclass : string; 
    hsubclass : string; 
    typemanage : string; 
    unitmanage : string; 
    unitdesc : string; 
    unitreceipt : string; 
    unitprep : string; 
    unitsale : string; 
    unitstock : string; 
    unitweight : string; 
    unitdimension : string; 
    unitvolume : string; 
    hucode : string; 
    rtoskuofpu : number; 
    rtoskuofipck : number; 
    rtoskuofpck : number; 
    rtoskuoflayer : number; 
    rtoskuofhu : number; 
    rtopckoflayer : number; 
    rtolayerofhu : number; 
    innaturalloss : number; 
    ounaturalloss : number; 
    costavginbound : number; 
    costavgoutbound : number; 
    costavg : number; 
    skulength : number; 
    skuwidth : number; 
    skuheight : number; 
    skugrossweight : number; 
    skuweight : number; 
    skuvolume : number; 
    pulength : number; 
    puwidth : number; 
    puheight : number; 
    pugrossweight : number; 
    puweight : number; 
    puvolume : number; 
    ipcklength : number; 
    ipckwidth : number; 
    ipckheight : number; 
    ipckgrossweight : number; 
    ipckweight : number; 
    ipckvolume : number; 
    pcklength : number; 
    pckwidth : number; 
    pckheight : number; 
    pckgrossweight : number; 
    pckweight : number; 
    pckvolume : number; 
    layerlength : number; 
    layerwidth : number; 
    layerheight : number; 
    layergrossweight : number; 
    layerweight : number; 
    layervolume : number; 
    hulength : number; 
    huwidth : number; 
    huheight : number; 
    hugrossweight : number; 
    huweight : number; 
    huvolume : number; 
    isdangerous : boolean; 
    ishighvalue : boolean; 
    isfastmove : boolean; 
    isslowmove : boolean; 
    isprescription : boolean; 
    isdlc : boolean; 
    ismaterial : boolean; 
    isunique : boolean; 
    isalcohol : boolean; 
    istemperature : boolean; 
    isdynamicpick : boolean; 
    isclusterpick : boolean;
    ismixingprep : boolean; 
    isfinishgoods : boolean; 
    isnaturalloss : boolean; 
    isbatchno : boolean; 
    ismeasurement : boolean; 
    roomtype : string; 
    tempmin : number; 
    tempmax : number; 
    alcmanage : string; 
    alccategory : string; 
    alccontent : string; 
    alccolor : string; 
    dangercategory : string; 
    dangerlevel : string; 
    stockthresholdmin : number; 
    stockthresholdmax : number; 
    spcrecvzone : string; 
    spcrecvaisle : string;
    spcrecvaisleto : string; 
    spcrecvbay : string;
    spcrecvbayto : string; 
    spcrecvlevel : string; 
    spcrecvlevelto : string; 
    spcrecvlocation : string; 
    spcprepzone : string; 
    spcdistzone : string; 
    spcdistshare : string; 
    spczonedelv : string; 
    orbitsource : string; 
    tflow : string; 
    datecreate : Date | string | null; 
    accncreate : string; 
    datemodify : Date | string | null; 
    accnmodify : string; 
    procmodify : string; 
    lasrecv : Date | string | null; 
    lasdelivery : Date | string | null; 
    lasbatchno : string; 
    laslotno : string; 
    lasdatemfg : Date | string | null; 
    lasdateexp : Date | string | null; 
    lasserialno : string; 

    rtoipckofpck : number;
    thname:string;
    // hdivisonname : string;
    hdivisionname:string;
    hdepartmentname : string; 
    hsubdepartname : string; 
    hclassname : string; 
    hsubclassname : string; 
    typemanagename : string; 
}

export interface product_at {
    orgcode: string;
    site: string;
    depot: string;
    spcarea: string;
    barcode: string;
    article: string;
    pv: number;
    lv: number;
    descalt: string;
    skulength: number;
    skuwidth: number;
    skuheight: number;
    skugrossweight: number;
    skuweight: number;
    skuvolume: number;
    rtoskuofpu: number;
    rtopckoflayer: number;
    rtolayerofhu: number;
    rtopckofpallet: number;
    rtoskuofipck: number;
    rtoskuofpck: number;
    rtoskuoflayer: number;
    rtoskuofhu: number;
    unitprep: string;
    unitreceipt: string;
    unitmanage: string;
    unitdesc: string;
    articletype: string;
}

// export class product_md extends product_ls  {
//     description: string; 
//     dlcall: number; 
//     dlcfactory: number; 
//     dlcwarehouse: number; 
//     dlcshop: number; 
//     dlconsumer: number; 
//     hdivison: string; 
//     hdepartment: string; 
//     hsubdepart: string; 
//     hclass: string; 
//     hsubclass: string; 
//     typemanage: string; 
//     unitmanage: string; 
//     unitreceipt: string; 
//     unitprep: string; 
//     unitsale: string; 
//     unitstock: string;
//     unitdesc: string;
//     unitweight: string; 
//     unitdimension: string; 
//     unitvolume: string; 
//     hucode: string; 
//     skulength: number; 
//     skuwidth: number; 
//     skuheight: number; 
//     skuweight: number; 
//     skuvolume: number; 
//     rtoskuofpu: number; 
//     rtoskuofipck: number; 
//     rtoskuofpck: number; 
//     rtoskuoflayer: number; 
//     rtoskuofhu: number;

//     rtoskuofipck:number;
//     rtoskuofpck:number;
//     rtoskuoflayer:number;
//     rtoskuofhu:number;

//     innaturalloss: number; 
//     ounaturalloss: number; 
//     costavg: number; 
//     pulength: number; 
//     puwidth: number; 
//     puheight: number; 
//     pugrossweight: number; 
//     puweight: number; 
//     puvolume: number; 
//     ipcklength: number; 
//     ipckwidth: number; 
//     ipckheight: number; 
//     ipckgrossweight: number; 
//     ipckweight: number; 
//     ipckvolume: number; 
//     pcklength: number; 
//     pckwidth: number; 
//     pckheight: number; 
//     pckgrossweight: number; 
//     pckweight: number; 
//     pckvolume: number; 
//     layerlength: number; 
//     layerwidth: number; 
//     layerheight: number; 
//     layergrossweight: number; 
//     layerweight: number; 
//     layervolume: number; 
//     hulength: number; 
//     huwidth: number; 
//     huheight: number; 
//     hugrossweight: number; 
//     huweight: number; 
//     huvolume: number; 
//     tempmin: number; 
//     tempmax: number; 
//     isdangerous: number; 
//     ishighvalue: number; 
//     isfastmove: number; 
//     isslowmove: number; 
//     isprescription: number; 
//     isdlc: number; 
//     ismaterial: number; 
//     isunique: number; 
//     isalcohol: number; 
//     istemperature: number; 
//     isimflammable: number; 
//     ismixingprep: number; 
//     isfinishgoods: number; 
//     isnaturalloss:number;
//     temptype: string; 
//     alcmanage: string; 
//     alccategory: string; 
//     alccontent: string; 
//     alccolor: string; 
//     dangercategory: string; 
//     dangerlevel: string; 
//     thresholdmin: number; 
//     spczone: string; 
//     spcbay: string; 
//     spclevel: string; 
//     spclocation: string; 
//     spchdivison: string; 
//     spchcategory: string; 
//     spcpivot: string; 
//     // cronhand: number; 
//     // cronblock: number; 
//     // crincmng: number; 
//     // croudeliv: number; 
//     laslotno: string; 
//     lasdatemfg: Date | string | null; 
//     lasdateexp: Date | string | null; 
//     lasserialno: string; 
//     datecreate: Date | string | null; 
//     accncreate: string; 
//     datemodify: Date | string | null; 
//     accnmodify: string; 
//     procmodify: string; 
//     rqdynamicpick:number;
//     rqbatchno:number;
// }
