using System;
using System.Data.SqlClient;
using Snaps.Helpers.StringExt;
using Snaps.Helpers.DbContext.SQLServer;
namespace Snaps.WMS {
    
    public partial class exSource_ops : IDisposable 
    {
        public exsFile fillexsfile(ref SqlDataReader r){ 
            exsFile rn = new exsFile(); 
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.fileid = (r.IsDBNull(3)) ? 0 :  r.GetDecimal(3);
            rn.filename = r["filename"].ToString();
            rn.filetype = r["filetype"].ToString();
            rn.filelength = (r.IsDBNull(6)) ? 0 :  r.GetDecimal(6);
            rn.imptype = r["imptype"].ToString();
            rn.datestart = (r.IsDBNull(8)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(8);
            rn.dateend = (r.IsDBNull(9)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(9);
            rn.opsperform = r["opsperform"].ToString();
            rn.opsins = (r.IsDBNull(11)) ? 0 :  r.GetDecimal(11);
            rn.opsupd = (r.IsDBNull(12)) ? 0 :  r.GetDecimal(12);
            rn.opsrem = (r.IsDBNull(13)) ? 0 :  r.GetDecimal(13);
            rn.opserr = (r.IsDBNull(14)) ? 0 :  r.GetDecimal(14);
            rn.opsdecstart = (r.IsDBNull(15)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(15);
            rn.opsimpstart = (r.IsDBNull(16)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(16);
            rn.tflow = r["tflow"].ToString();
            rn.datecreate = (r.IsDBNull(18)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(18);
            rn.accncreate = r["accncreate"].ToString();
            return rn;
        }
        
        private exsBarcode fillBarcode(ref SqlDataReader r){ 
            exsBarcode rn = new exsBarcode(); 
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            //rn.spcarea = r["spcarea"].ToString();
            rn.article = r["article"].ToString();
            rn.pv = (r.IsDBNull(5)) ? 0 :  r.GetInt32(5);
            rn.lv = (r.IsDBNull(6)) ? 0 :  r.GetInt32(6);
            rn.barops = r["barops"].ToString();
            rn.barcode = r["barcode"].ToString();
            rn.bartype = r["bartype"].ToString();
            rn.thcode = r["thcode"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(16)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(16);
            rn.rowid = (r.IsDBNull(17)) ? 0 :  r.GetInt32(17);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsBarcode o, string fileId) { 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["article"].Value = o.article;
            x.Parameters["pv"].Value = o.pv;
            x.Parameters["lv"].Value = o.lv;
            x.Parameters["barops"].Value = o.barops;
            x.Parameters["barcode"].Value = o.barcode;
            x.Parameters["bartype"].Value = o.bartype;
            x.Parameters["thcode"].Value = o.thcode;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["fileid"].Value = fileId;
            x.Parameters["rowops"].Value = o.rowops;
            //x.Parameters["ermsg"].Value = o.ermsg;
           // x.Parameters["dateops"].Value = o.dateops;
           // x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsBarcode o,string cmd =""){ 
            SqlCommand cm = new SqlCommand(cmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.article,"article");
            cm.snapsPar(o.pv,"pv");
            cm.snapsPar(o.lv,"lv");
            cm.snapsPar(o.barops,"barops");
            cm.snapsPar(o.barcode,"barcode");
            cm.snapsPar(o.bartype,"bartype");
            cm.snapsPar(o.thcode,"thcode");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.rowid,"rowid");
            return cm;
        }

        private exsThirdparty fillThirdparty(ref SqlDataReader r){ 
            exsThirdparty rn = new exsThirdparty();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.thtype = r["thtype"].ToString();
            rn.thbutype = r["thbutype"].ToString();
            rn.thcode = r["thcode"].ToString();
            rn.thcodealt = r["thcodealt"].ToString();
            rn.vatcode = r["vatcode"].ToString();
            rn.thname = r["thname"].ToString();
            rn.thnamealt = r["thnamealt"].ToString();
            rn.addressln1 = r["addressln1"].ToString();
            rn.addressln2 = r["addressln2"].ToString();
            rn.addressln3 = r["addressln3"].ToString();
            rn.subdistrict = r["subdistrict"].ToString();
            rn.district = r["district"].ToString();
            rn.city = r["city"].ToString();
            rn.country = r["country"].ToString();
            rn.postcode = r["postcode"].ToString();
            rn.region = r["region"].ToString();
            rn.telephone = r["telephone"].ToString();
            rn.email = r["email"].ToString();
            rn.thgroup = r["thgroup"].ToString();
            rn.thcomment = r["thcomment"].ToString();
            rn.throuteformat = r["throuteformat"].ToString();
            rn.plandelivery = (r.IsDBNull(25)) ? 0 :  r.GetInt32(25);
            rn.naturalloss = (r.IsDBNull(26)) ? 0 :  r.GetInt32(26);
            rn.mapaddress = r["mapaddress"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(33)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(33);
            rn.rowid = (r.IsDBNull(34)) ? 0 :  r.GetInt32(34);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsThirdparty o,string fileId) { 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["thtype"].Value = o.thtype;
            x.Parameters["thbutype"].Value = o.thbutype;
            x.Parameters["thcode"].Value = o.thcode;
            x.Parameters["thcodealt"].Value = o.thcodealt;
            x.Parameters["vatcode"].Value = o.vatcode;
            x.Parameters["thname"].Value = o.thname;
            x.Parameters["thnamealt"].Value = o.thnamealt;
            x.Parameters["addressln1"].Value = o.addressln1;
            x.Parameters["addressln2"].Value = o.addressln2;
            x.Parameters["addressln3"].Value = o.addressln3;
            x.Parameters["subdistrict"].Value = o.subdistrict;
            x.Parameters["district"].Value = o.district;
            x.Parameters["city"].Value = o.city;
            x.Parameters["country"].Value = o.country;
            x.Parameters["postcode"].Value = o.postcode;
            x.Parameters["region"].Value = o.region;
            x.Parameters["telephone"].Value = o.telephone;
            x.Parameters["email"].Value = o.email;
            x.Parameters["thgroup"].Value = o.thgroup;
            x.Parameters["thcomment"].Value = o.thcomment;
            x.Parameters["throuteformat"].Value = o.throuteformat;
            x.Parameters["plandelivery"].Value = o.plandelivery;
            x.Parameters["naturalloss"].Value = o.naturalloss;
            x.Parameters["mapaddress"].Value = o.mapaddress;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["fileid"].Value = fileId;
            x.Parameters["rowops"].Value = o.rowops;
            x.Parameters["ermsg"].Value = o.ermsg;
            // x.Parameters["dateops"].Value = o.dateops;
            // x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsThirdparty o,string sqlcmd = ""){ 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            //cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.thtype,"thtype");
            cm.snapsPar(o.thbutype,"thbutype");
            cm.snapsPar(o.thcode,"thcode");
            cm.snapsPar(o.thcodealt,"thcodealt");
            cm.snapsPar(o.vatcode,"vatcode");
            cm.snapsPar(o.thname,"thname");
            cm.snapsPar(o.thnamealt,"thnamealt");
            cm.snapsPar(o.addressln1,"addressln1");
            cm.snapsPar(o.addressln2,"addressln2");
            cm.snapsPar(o.addressln3,"addressln3");
            cm.snapsPar(o.subdistrict,"subdistrict");
            cm.snapsPar(o.district,"district");
            cm.snapsPar(o.city,"city");
            cm.snapsPar(o.country,"country");
            cm.snapsPar(o.postcode,"postcode");
            cm.snapsPar(o.region,"region");
            cm.snapsPar(o.telephone,"telephone");
            cm.snapsPar(o.email,"email");
            cm.snapsPar(o.thgroup,"thgroup");
            cm.snapsPar(o.thcomment,"thcomment");
            cm.snapsPar(o.throuteformat,"throuteformat");
            cm.snapsPar(o.plandelivery,"plandelivery");
            cm.snapsPar(o.naturalloss,"naturalloss");
            cm.snapsPar(o.mapaddress,"mapaddress");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            // cm.snapsPar(o.dateops,"dateops");
            // cm.snapsPar(o.rowid,"rowid");
            return cm;
        }
    
        private exsProduct fillProduct(ref SqlDataReader r) { 
            exsProduct rn = new exsProduct();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.article = r["article"].ToString();
            rn.articletype = r["articletype"].ToString();
            rn.pv = (r.IsDBNull(6)) ? 0 :  r.GetInt32(6);
            rn.lv = (r.IsDBNull(7)) ? 0 :  r.GetInt32(7);
            rn.description = r["description"].ToString();
            rn.descalt = r["descalt"].ToString();
            rn.thcode = r["thcode"].ToString();
            rn.dlcall = (r.IsDBNull(11)) ? 0 :  r.GetInt32(11);
            rn.dlcfactory = (r.IsDBNull(12)) ? 0 :  r.GetInt32(12);
            rn.dlcwarehouse = (r.IsDBNull(13)) ? 0 :  r.GetInt32(13);
            rn.dlcshop = (r.IsDBNull(14)) ? 0 :  r.GetInt32(14);
            rn.dlconsumer = (r.IsDBNull(15)) ? 0 :  r.GetInt32(15);
            rn.hdivison = r["hdivison"].ToString();
            rn.hdepartment = r["hdepartment"].ToString();
            rn.hsubdepart = r["hsubdepart"].ToString();
            rn.hclass = r["hclass"].ToString();
            rn.hsubclass = r["hsubclass"].ToString();
            rn.typemanage = r["typemanage"].ToString();
            rn.unitmanage = r["unitmanage"].ToString();
            rn.unitdesc = r["unitdesc"].ToString();
            rn.unitreceipt = r["unitreceipt"].ToString();
            rn.unitprep = r["unitprep"].ToString();
            rn.unitsale = r["unitsale"].ToString();
            rn.unitstock = r["unitstock"].ToString();
            rn.unitweight = r["unitweight"].ToString();
            rn.unitdimension = r["unitdimension"].ToString();
            rn.unitvolume = r["unitvolume"].ToString();
            rn.hucode = r["hucode"].ToString();
            rn.rtoskuofpu = (r.IsDBNull(32)) ? 0 :  r.GetInt32(32);
            rn.rtoskuofipck = (r.IsDBNull(33)) ? 0 :  r.GetInt32(33);
            rn.rtoskuofpck = (r.IsDBNull(34)) ? 0 :  r.GetInt32(34);
            rn.rtoskuoflayer = (r.IsDBNull(35)) ? 0 :  r.GetInt32(35);
            rn.rtoskuofhu = (r.IsDBNull(36)) ? 0 :  r.GetInt32(36);
            rn.rtopckoflayer = (r.IsDBNull(37)) ? 0 :  r.GetInt32(37);
            rn.rtolayerofhu = (r.IsDBNull(38)) ? 0 :  r.GetInt32(38);
            rn.innaturalloss = (r.IsDBNull(39)) ? 0 :  r.GetInt32(39);
            rn.ounaturalloss = (r.IsDBNull(40)) ? 0 :  r.GetInt32(40);
            rn.costinbound =  (r.IsDBNull(41)) ? 0 : r.GetDecimal(41);
            rn.costoutbound =  (r.IsDBNull(42)) ? 0 : r.GetDecimal(42);
            rn.costavg =  (r.IsDBNull(43)) ? 0 : r.GetDecimal(43);
            rn.skulength =  (r.IsDBNull(44)) ? 0 : r.GetDecimal(44);
            rn.skuwidth =  (r.IsDBNull(45)) ? 0 : r.GetDecimal(45);
            rn.skuheight =  (r.IsDBNull(46)) ? 0 : r.GetDecimal(46);
            rn.skugrossweight =  (r.IsDBNull(47)) ? 0 : r.GetDecimal(47);
            rn.skuweight =  (r.IsDBNull(48)) ? 0 : r.GetDecimal(48);
            rn.skuvolume =  (r.IsDBNull(49)) ? 0 : r.GetDecimal(49);
            rn.pulength =  (r.IsDBNull(50)) ? 0 : r.GetDecimal(50);
            rn.puwidth =  (r.IsDBNull(51)) ? 0 : r.GetDecimal(51);
            rn.puheight =  (r.IsDBNull(52)) ? 0 : r.GetDecimal(52);
            rn.pugrossweight =  (r.IsDBNull(53)) ? 0 : r.GetDecimal(53);
            rn.puweight =  (r.IsDBNull(54)) ? 0 : r.GetDecimal(54);
            rn.puvolume =  (r.IsDBNull(55)) ? 0 : r.GetDecimal(55);
            rn.ipcklength =  (r.IsDBNull(56)) ? 0 : r.GetDecimal(56);
            rn.ipckwidth =  (r.IsDBNull(57)) ? 0 : r.GetDecimal(57);
            rn.ipckheight =  (r.IsDBNull(58)) ? 0 : r.GetDecimal(58);
            rn.ipckgrossweight =  (r.IsDBNull(59)) ? 0 : r.GetDecimal(59);
            rn.ipckweight =  (r.IsDBNull(60)) ? 0 : r.GetDecimal(60);
            rn.ipckvolume =  (r.IsDBNull(61)) ? 0 : r.GetDecimal(61);
            rn.pcklength =  (r.IsDBNull(62)) ? 0 : r.GetDecimal(62);
            rn.pckwidth =  (r.IsDBNull(63)) ? 0 : r.GetDecimal(63);
            rn.pckheight =  (r.IsDBNull(64)) ? 0 : r.GetDecimal(64);
            rn.pckgrossweight =  (r.IsDBNull(65)) ? 0 : r.GetDecimal(65);
            rn.pckweight =  (r.IsDBNull(66)) ? 0 : r.GetDecimal(66);
            rn.pckvolume =  (r.IsDBNull(67)) ? 0 : r.GetDecimal(67);
            rn.layerlength =  (r.IsDBNull(68)) ? 0 : r.GetDecimal(68);
            rn.layerwidth =  (r.IsDBNull(69)) ? 0 : r.GetDecimal(69);
            rn.layerheight =  (r.IsDBNull(70)) ? 0 : r.GetDecimal(70);
            rn.layergrossweight =  (r.IsDBNull(71)) ? 0 : r.GetDecimal(71);
            rn.layerweight =  (r.IsDBNull(72)) ? 0 : r.GetDecimal(72);
            rn.layervolume =  (r.IsDBNull(73)) ? 0 : r.GetDecimal(73);
            rn.hulength =  (r.IsDBNull(74)) ? 0 : r.GetDecimal(74);
            rn.huwidth =  (r.IsDBNull(75)) ? 0 : r.GetDecimal(75);
            rn.huheight =  (r.IsDBNull(76)) ? 0 : r.GetDecimal(76);
            rn.hugrossweight =  (r.IsDBNull(77)) ? 0 : r.GetDecimal(77);
            rn.huweight =  (r.IsDBNull(78)) ? 0 : r.GetDecimal(78);
            rn.huvolume =  (r.IsDBNull(79)) ? 0 : r.GetDecimal(79);
            rn.isdangerous = (r.IsDBNull(80)) ? 0 :  r.GetInt32(80);
            rn.ishighvalue = (r.IsDBNull(81)) ? 0 :  r.GetInt32(81);
            rn.isfastmove = (r.IsDBNull(82)) ? 0 :  r.GetInt32(82);
            rn.isslowmove = (r.IsDBNull(83)) ? 0 :  r.GetInt32(83);
            rn.isprescription = (r.IsDBNull(84)) ? 0 :  r.GetInt32(84);
            rn.isdlc = (r.IsDBNull(85)) ? 0 :  r.GetInt32(85);
            rn.ismaterial = (r.IsDBNull(86)) ? 0 :  r.GetInt32(86);
            rn.isunique = (r.IsDBNull(87)) ? 0 :  r.GetInt32(87);
            rn.isalcohol = (r.IsDBNull(88)) ? 0 :  r.GetInt32(88);
            rn.istemperature = (r.IsDBNull(89)) ? 0 :  r.GetInt32(89);
            rn.isdynamicpick = (r.IsDBNull(90)) ? 0 :  r.GetInt32(90);
            rn.ismixingprep = (r.IsDBNull(91)) ? 0 :  r.GetInt32(91);
            rn.isfinishgoods = (r.IsDBNull(92)) ? 0 :  r.GetInt32(92);
            rn.isnaturalloss = (r.IsDBNull(93)) ? 0 :  r.GetInt32(93);
            rn.isbatchno = (r.IsDBNull(94)) ? 0 :  r.GetInt32(94);
            rn.ismeasurement = (r.IsDBNull(95)) ? 0 :  r.GetInt32(95);
            rn.roomtype = r["roomtype"].ToString();
            rn.tempmin = (r.IsDBNull(97)) ? 0 :  r.GetInt32(97);
            rn.tempmax = (r.IsDBNull(98)) ? 0 :  r.GetInt32(98);
            rn.alcmanage = r["alcmanage"].ToString();
            rn.alccategory = r["alccategory"].ToString();
            rn.alccontent = r["alccontent"].ToString();
            rn.alccolor = r["alccolor"].ToString();
            rn.dangercategory = r["dangercategory"].ToString();
            rn.dangerlevel = r["dangerlevel"].ToString();
            rn.stockthresholdmin = (r.IsDBNull(105)) ? 0 :  r.GetInt32(105);
            rn.stockthresholdmax = (r.IsDBNull(106)) ? 0 :  r.GetInt32(106);
            rn.spcrecvzone = r["spcrecvzone"].ToString();
            rn.spcrecvaisle = r["spcrecvaisle"].ToString();
            rn.spcrecvbay = r["spcrecvbay"].ToString();
            rn.spcrecvlevel = r["spcrecvlevel"].ToString();
            rn.spcrecvlocation = r["spcrecvlocation"].ToString();
            rn.spcprepzone = r["spcprepzone"].ToString();
            rn.spcdistzone = r["spcdistzone"].ToString();
            rn.spcdistshare = r["spcdistshare"].ToString();
            rn.spczonedelv = r["spczonedelv"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.datecreate = (r.IsDBNull(120)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(120);
            rn.dateops = (r.IsDBNull(121)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(121);
            rn.ermsg = r["ermsg"].ToString();
            rn.rowid = (r.IsDBNull(123)) ? 0 :  r.GetInt32(123);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsProduct o,string fildId){ 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["article"].Value = o.article;
            x.Parameters["articletype"].Value = o.articletype;
            x.Parameters["pv"].Value = o.pv;
            x.Parameters["lv"].Value = o.lv;
            x.Parameters["description"].Value = o.description;
            x.Parameters["descalt"].Value = o.descalt;
            x.Parameters["thcode"].Value = o.thcode;
            x.Parameters["dlcall"].Value = o.dlcall;
            x.Parameters["dlcfactory"].Value = o.dlcfactory;
            x.Parameters["dlcwarehouse"].Value = o.dlcwarehouse;
            x.Parameters["dlcshop"].Value = o.dlcshop;
            x.Parameters["dlconsumer"].Value = o.dlconsumer;
            x.Parameters["hdivison"].Value = o.hdivison;
            x.Parameters["hdepartment"].Value = o.hdepartment;
            x.Parameters["hsubdepart"].Value = o.hsubdepart;
            x.Parameters["hclass"].Value = o.hclass;
            x.Parameters["hsubclass"].Value = o.hsubclass;
            x.Parameters["typemanage"].Value = o.typemanage;
            x.Parameters["unitmanage"].Value = o.unitmanage;
            x.Parameters["unitdesc"].Value = o.unitdesc;
            x.Parameters["unitreceipt"].Value = o.unitreceipt;
            x.Parameters["unitprep"].Value = o.unitprep;
            x.Parameters["unitsale"].Value = o.unitsale;
            x.Parameters["unitstock"].Value = o.unitstock;
            x.Parameters["unitweight"].Value = o.unitweight;
            x.Parameters["unitdimension"].Value = o.unitdimension;
            x.Parameters["unitvolume"].Value = o.unitvolume;
            x.Parameters["hucode"].Value = o.hucode;
            x.Parameters["rtoskuofpu"].Value = o.rtoskuofpu;
            x.Parameters["rtoskuofipck"].Value = o.rtoskuofipck;
            x.Parameters["rtoskuofpck"].Value = o.rtoskuofpck;
            x.Parameters["rtoskuoflayer"].Value = o.rtoskuoflayer;
            x.Parameters["rtoskuofhu"].Value = o.rtoskuofhu;
            x.Parameters["rtopckoflayer"].Value = o.rtopckoflayer;
            x.Parameters["rtolayerofhu"].Value = o.rtolayerofhu;
            x.Parameters["innaturalloss"].Value = o.innaturalloss;
            x.Parameters["ounaturalloss"].Value = o.ounaturalloss;
            x.Parameters["costinbound"].Value = o.costinbound;
            x.Parameters["costoutbound"].Value = o.costoutbound;
            x.Parameters["costavg"].Value = o.costavg;
            x.Parameters["skulength"].Value = o.skulength;
            x.Parameters["skuwidth"].Value = o.skuwidth;
            x.Parameters["skuheight"].Value = o.skuheight;
            x.Parameters["skugrossweight"].Value = o.skugrossweight;
            x.Parameters["skuweight"].Value = o.skuweight;
            x.Parameters["skuvolume"].Value = o.skuvolume;
            x.Parameters["pulength"].Value = o.pulength;
            x.Parameters["puwidth"].Value = o.puwidth;
            x.Parameters["puheight"].Value = o.puheight;
            x.Parameters["pugrossweight"].Value = o.pugrossweight;
            x.Parameters["puweight"].Value = o.puweight;
            x.Parameters["puvolume"].Value = o.puvolume;
            x.Parameters["ipcklength"].Value = o.ipcklength;
            x.Parameters["ipckwidth"].Value = o.ipckwidth;
            x.Parameters["ipckheight"].Value = o.ipckheight;
            x.Parameters["ipckgrossweight"].Value = o.ipckgrossweight;
            x.Parameters["ipckweight"].Value = o.ipckweight;
            x.Parameters["ipckvolume"].Value = o.ipckvolume;
            x.Parameters["pcklength"].Value = o.pcklength;
            x.Parameters["pckwidth"].Value = o.pckwidth;
            x.Parameters["pckheight"].Value = o.pckheight;
            x.Parameters["pckgrossweight"].Value = o.pckgrossweight;
            x.Parameters["pckweight"].Value = o.pckweight;
            x.Parameters["pckvolume"].Value = o.pckvolume;
            x.Parameters["layerlength"].Value = o.layerlength;
            x.Parameters["layerwidth"].Value = o.layerwidth;
            x.Parameters["layerheight"].Value = o.layerheight;
            x.Parameters["layergrossweight"].Value = o.layergrossweight;
            x.Parameters["layerweight"].Value = o.layerweight;
            x.Parameters["layervolume"].Value = o.layervolume;
            x.Parameters["hulength"].Value = o.hulength;
            x.Parameters["huwidth"].Value = o.huwidth;
            x.Parameters["huheight"].Value = o.huheight;
            x.Parameters["hugrossweight"].Value = o.hugrossweight;
            x.Parameters["huweight"].Value = o.huweight;
            x.Parameters["huvolume"].Value = o.huvolume;
            x.Parameters["isdangerous"].Value = o.isdangerous;
            x.Parameters["ishighvalue"].Value = o.ishighvalue;
            x.Parameters["isfastmove"].Value = o.isfastmove;
            x.Parameters["isslowmove"].Value = o.isslowmove;
            x.Parameters["isprescription"].Value = o.isprescription;
            x.Parameters["isdlc"].Value = o.isdlc;
            x.Parameters["ismaterial"].Value = o.ismaterial;
            x.Parameters["isunique"].Value = o.isunique;
            x.Parameters["isalcohol"].Value = o.isalcohol;
            x.Parameters["istemperature"].Value = o.istemperature;
            x.Parameters["isdynamicpick"].Value = o.isdynamicpick;
            x.Parameters["ismixingprep"].Value = o.ismixingprep;
            x.Parameters["isfinishgoods"].Value = o.isfinishgoods;
            x.Parameters["isnaturalloss"].Value = o.isnaturalloss;
            x.Parameters["isbatchno"].Value = o.isbatchno;
            x.Parameters["ismeasurement"].Value = o.ismeasurement;
            x.Parameters["roomtype"].Value = o.roomtype;
            x.Parameters["tempmin"].Value = o.tempmin;
            x.Parameters["tempmax"].Value = o.tempmax;
            x.Parameters["alcmanage"].Value = o.alcmanage;
            x.Parameters["alccategory"].Value = o.alccategory;
            x.Parameters["alccontent"].Value = o.alccontent;
            x.Parameters["alccolor"].Value = o.alccolor;
            x.Parameters["dangercategory"].Value = o.dangercategory;
            x.Parameters["dangerlevel"].Value = o.dangerlevel;
            x.Parameters["stockthresholdmin"].Value = o.stockthresholdmin;
            x.Parameters["stockthresholdmax"].Value = o.stockthresholdmax;
            x.Parameters["spcrecvzone"].Value = o.spcrecvzone;
            x.Parameters["spcrecvaisle"].Value = o.spcrecvaisle;
            x.Parameters["spcrecvbay"].Value = o.spcrecvbay;
            x.Parameters["spcrecvlevel"].Value = o.spcrecvlevel;
            x.Parameters["spcrecvlocation"].Value = o.spcrecvlocation;
            x.Parameters["spcprepzone"].Value = o.spcprepzone;
            x.Parameters["spcdistzone"].Value = o.spcdistzone;
            x.Parameters["spcdistshare"].Value = o.spcdistshare;
            x.Parameters["spczonedelv"].Value = o.spczonedelv;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["fileid"].Value = fildId;
            x.Parameters["rowops"].Value = o.rowops;
            //x.Parameters["datecreate"].Value = o.datecreate;
            //x.Parameters["dateops"].Value = o.dateops;
            x.Parameters["ermsg"].Value = o.ermsg;
            x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsProduct o,string sqlcmd = "") { 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            //cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.article,"article");
            cm.snapsPar(o.articletype,"articletype");
            cm.snapsPar(o.pv,"pv");
            cm.snapsPar(o.lv,"lv");
            cm.snapsPar(o.description,"description");
            cm.snapsPar(o.descalt,"descalt");
            cm.snapsPar(o.thcode,"thcode");
            cm.snapsPar(o.dlcall,"dlcall");
            cm.snapsPar(o.dlcfactory,"dlcfactory");
            cm.snapsPar(o.dlcwarehouse,"dlcwarehouse");
            cm.snapsPar(o.dlcshop,"dlcshop");
            cm.snapsPar(o.dlconsumer,"dlconsumer");
            cm.snapsPar(o.hdivison,"hdivison");
            cm.snapsPar(o.hdepartment,"hdepartment");
            cm.snapsPar(o.hsubdepart,"hsubdepart");
            cm.snapsPar(o.hclass,"hclass");
            cm.snapsPar(o.hsubclass,"hsubclass");
            cm.snapsPar(o.typemanage,"typemanage");
            cm.snapsPar(o.unitmanage,"unitmanage");
            cm.snapsPar(o.unitdesc,"unitdesc");
            cm.snapsPar(o.unitreceipt,"unitreceipt");
            cm.snapsPar(o.unitprep,"unitprep");
            cm.snapsPar(o.unitsale,"unitsale");
            cm.snapsPar(o.unitstock,"unitstock");
            cm.snapsPar(o.unitweight,"unitweight");
            cm.snapsPar(o.unitdimension,"unitdimension");
            cm.snapsPar(o.unitvolume,"unitvolume");
            cm.snapsPar(o.hucode,"hucode");
            cm.snapsPar(o.rtoskuofpu,"rtoskuofpu");
            cm.snapsPar(o.rtoskuofipck,"rtoskuofipck");
            cm.snapsPar(o.rtoskuofpck,"rtoskuofpck");
            cm.snapsPar(o.rtoskuoflayer,"rtoskuoflayer");
            cm.snapsPar(o.rtoskuofhu,"rtoskuofhu");
            cm.snapsPar(o.rtopckoflayer,"rtopckoflayer");
            cm.snapsPar(o.rtolayerofhu,"rtolayerofhu");
            cm.snapsPar(o.innaturalloss,"innaturalloss");
            cm.snapsPar(o.ounaturalloss,"ounaturalloss");
            cm.snapsPar(o.costinbound,"costinbound");
            cm.snapsPar(o.costoutbound,"costoutbound");
            cm.snapsPar(o.costavg,"costavg");
            cm.snapsPar(o.skulength,"skulength");
            cm.snapsPar(o.skuwidth,"skuwidth");
            cm.snapsPar(o.skuheight,"skuheight");
            cm.snapsPar(o.skugrossweight,"skugrossweight");
            cm.snapsPar(o.skuweight,"skuweight");
            cm.snapsPar(o.skuvolume,"skuvolume");
            cm.snapsPar(o.pulength,"pulength");
            cm.snapsPar(o.puwidth,"puwidth");
            cm.snapsPar(o.puheight,"puheight");
            cm.snapsPar(o.pugrossweight,"pugrossweight");
            cm.snapsPar(o.puweight,"puweight");
            cm.snapsPar(o.puvolume,"puvolume");
            cm.snapsPar(o.ipcklength,"ipcklength");
            cm.snapsPar(o.ipckwidth,"ipckwidth");
            cm.snapsPar(o.ipckheight,"ipckheight");
            cm.snapsPar(o.ipckgrossweight,"ipckgrossweight");
            cm.snapsPar(o.ipckweight,"ipckweight");
            cm.snapsPar(o.ipckvolume,"ipckvolume");
            cm.snapsPar(o.pcklength,"pcklength");
            cm.snapsPar(o.pckwidth,"pckwidth");
            cm.snapsPar(o.pckheight,"pckheight");
            cm.snapsPar(o.pckgrossweight,"pckgrossweight");
            cm.snapsPar(o.pckweight,"pckweight");
            cm.snapsPar(o.pckvolume,"pckvolume");
            cm.snapsPar(o.layerlength,"layerlength");
            cm.snapsPar(o.layerwidth,"layerwidth");
            cm.snapsPar(o.layerheight,"layerheight");
            cm.snapsPar(o.layergrossweight,"layergrossweight");
            cm.snapsPar(o.layerweight,"layerweight");
            cm.snapsPar(o.layervolume,"layervolume");
            cm.snapsPar(o.hulength,"hulength");
            cm.snapsPar(o.huwidth,"huwidth");
            cm.snapsPar(o.huheight,"huheight");
            cm.snapsPar(o.hugrossweight,"hugrossweight");
            cm.snapsPar(o.huweight,"huweight");
            cm.snapsPar(o.huvolume,"huvolume");
            cm.snapsPar(o.isdangerous,"isdangerous");
            cm.snapsPar(o.ishighvalue,"ishighvalue");
            cm.snapsPar(o.isfastmove,"isfastmove");
            cm.snapsPar(o.isslowmove,"isslowmove");
            cm.snapsPar(o.isprescription,"isprescription");
            cm.snapsPar(o.isdlc,"isdlc");
            cm.snapsPar(o.ismaterial,"ismaterial");
            cm.snapsPar(o.isunique,"isunique");
            cm.snapsPar(o.isalcohol,"isalcohol");
            cm.snapsPar(o.istemperature,"istemperature");
            cm.snapsPar(o.isdynamicpick,"isdynamicpick");
            cm.snapsPar(o.ismixingprep,"ismixingprep");
            cm.snapsPar(o.isfinishgoods,"isfinishgoods");
            cm.snapsPar(o.isnaturalloss,"isnaturalloss");
            cm.snapsPar(o.isbatchno,"isbatchno");
            cm.snapsPar(o.ismeasurement,"ismeasurement");
            cm.snapsPar(o.roomtype,"roomtype");
            cm.snapsPar(o.tempmin,"tempmin");
            cm.snapsPar(o.tempmax,"tempmax");
            cm.snapsPar(o.alcmanage,"alcmanage");
            cm.snapsPar(o.alccategory,"alccategory");
            cm.snapsPar(o.alccontent,"alccontent");
            cm.snapsPar(o.alccolor,"alccolor");
            cm.snapsPar(o.dangercategory,"dangercategory");
            cm.snapsPar(o.dangerlevel,"dangerlevel");
            cm.snapsPar(o.stockthresholdmin,"stockthresholdmin");
            cm.snapsPar(o.stockthresholdmax,"stockthresholdmax");
            cm.snapsPar(o.spcrecvzone,"spcrecvzone");
            cm.snapsPar(o.spcrecvaisle,"spcrecvaisle");
            cm.snapsPar(o.spcrecvbay,"spcrecvbay");
            cm.snapsPar(o.spcrecvlevel,"spcrecvlevel");
            cm.snapsPar(o.spcrecvlocation,"spcrecvlocation");
            cm.snapsPar(o.spcprepzone,"spcprepzone");
            cm.snapsPar(o.spcdistzone,"spcdistzone");
            cm.snapsPar(o.spcdistshare,"spcdistshare");
            cm.snapsPar(o.spczonedelv,"spczonedelv");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            //cm.snapsPar(o.datecreate,"datecreate");
            //cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.rowid,"rowid");
            return cm;
        }

        private exsInbound fillInbound(ref SqlDataReader r) { 
            exsInbound rn = new exsInbound();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.thcode = r["thcode"].ToString();
            rn.intype = r["intype"].ToString();
            rn.subtype = r["subtype"].ToString();
            rn.inorder = r["inorder"].ToString();
            rn.dateorder = (r.IsDBNull(8)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(8);
            rn.dateplan = (r.IsDBNull(9)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(9);
            rn.dateexpire = (r.IsDBNull(10)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(10);
            rn.inpriority = (r.IsDBNull(11)) ? 0 :  r.GetInt32(11);
            rn.inflag = r["inflag"].ToString();
            rn.inpromo = r["inpromo"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(19)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(19);
            rn.rowid = (r.IsDBNull(20)) ? 0 :  r.GetInt32(20);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsInbound o,string fildId){
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["thcode"].Value = o.thcode;
            x.Parameters["intype"].Value = o.intype;
            x.Parameters["subtype"].Value = o.subtype;
            x.Parameters["inorder"].Value = o.inorder;
            x.Parameters["dateorder"].Value = o.dateorder;
            x.Parameters["dateplan"].Value = o.dateplan;
            x.Parameters["dateexpire"].Value = o.dateexpire;
            x.Parameters["inpriority"].Value = o.inpriority;
            x.Parameters["inflag"].Value = o.inflag;
            x.Parameters["inpromo"].Value = o.inpromo;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["fileid"].Value = fildId;
            x.Parameters["rowops"].Value = o.rowops;
            x.Parameters["ermsg"].Value = o.ermsg;
            x.Parameters["dateops"].Value = o.dateops;
            x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsInbound o,string sqlcmd = "") { 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.thcode,"thcode");
            cm.snapsPar(o.intype,"intype");
            cm.snapsPar(o.subtype,"subtype");
            cm.snapsPar(o.inorder,"inorder");
            cm.snapsPar(o.dateorder,"dateorder");
            cm.snapsPar(o.dateplan,"dateplan");
            cm.snapsPar(o.dateexpire,"dateexpire");
            cm.snapsPar(o.inpriority,"inpriority");
            cm.snapsPar(o.inflag,"inflag");
            cm.snapsPar(o.inpromo,"inpromo");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.rowid,"rowid");
            return cm;
        }

        private exsInbouln fillInbouln(ref SqlDataReader r) { 
            exsInbouln rn = new exsInbouln();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.inorder = r["inorder"].ToString();
            rn.inln = r["inln"].ToString();
            rn.inrefno = r["inrefno"].ToString();
            rn.inrefln = r["inrefln"].ToString();
            rn.article = r["article"].ToString();
            rn.pv = (r.IsDBNull(9)) ? 0 :  r.GetInt32(9);
            rn.lv = (r.IsDBNull(10)) ? 0 :  r.GetInt32(10);
            rn.unitops = r["unitops"].ToString();
            rn.qtysku = (r.IsDBNull(12)) ? 0 :  r.GetInt32(12);
            rn.qtypu = (r.IsDBNull(13)) ? 0 :  r.GetInt32(13);
            rn.qtyweight =  (r.IsDBNull(14)) ? 0 : r.GetDecimal(14);
            rn.batchno = r["batchno"].ToString();
            rn.lotno = r["lotno"].ToString();
            rn.expdate = (r.IsDBNull(17)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(17);
            rn.serialno = r["serialno"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(24)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(24);
            rn.rowid = (r.IsDBNull(25)) ? 0 :  r.GetInt32(25);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsInbouln o,string fildId){ 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["inorder"].Value = o.inorder;
            x.Parameters["inln"].Value = o.inln;
            x.Parameters["inrefno"].Value = o.inrefno;
            x.Parameters["inrefln"].Value = o.inrefln;
            x.Parameters["article"].Value = o.article;
            x.Parameters["pv"].Value = o.pv;
            x.Parameters["lv"].Value = o.lv;
            x.Parameters["unitops"].Value = o.unitops;
            x.Parameters["qtysku"].Value = o.qtysku;
            x.Parameters["qtypu"].Value = o.qtypu;
            x.Parameters["qtyweight"].Value = o.qtyweight;
            x.Parameters["batchno"].Value = o.batchno;
            x.Parameters["lotno"].Value = o.lotno;
            if (o.expdate.HasValue) { 
                x.Parameters["expdate"].Value = o.expdate;
            }else { 
                x.Parameters["expdate"].Value = DBNull.Value;
            }
            x.Parameters["serialno"].Value = o.serialno;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["fileid"].Value = fildId;
            x.Parameters["rowops"].Value = o.rowops;
            x.Parameters["ermsg"].Value = o.ermsg;
            x.Parameters["dateops"].Value = o.dateops;
            x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsInbouln o,string sqlcmd = "") { 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            //cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.inorder,"inorder");
            cm.snapsPar(o.inln,"inln");
            cm.snapsPar(o.inrefno,"inrefno");
            cm.snapsPar(o.inrefln,"inrefln");
            cm.snapsPar(o.article,"article");
            cm.snapsPar(o.pv,"pv");
            cm.snapsPar(o.lv,"lv");
            cm.snapsPar(o.unitops,"unitops");
            cm.snapsPar(o.qtysku,"qtysku");
            cm.snapsPar(o.qtypu,"qtypu");
            cm.snapsPar(o.qtyweight,"qtyweight");
            cm.snapsPar(o.batchno,"batchno");
            cm.snapsPar(o.lotno,"lotno");
            cm.snapsPar(o.expdate,"expdate");
            cm.snapsPar(o.serialno,"serialno");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.rowid,"rowid");
            return cm;
        }

        private exsOutbound fillOutbound(ref SqlDataReader r) { 
            exsOutbound rn = new exsOutbound();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.ouorder = r["ouorder"].ToString();
            rn.outype = r["outype"].ToString();
            rn.ousubtype = r["ousubtype"].ToString();
            rn.thcode = r["thcode"].ToString();
            rn.dateorder = (r.IsDBNull(8)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(8);
            rn.dateprep = (r.IsDBNull(9)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(9);
            rn.dateexpire = (r.IsDBNull(10)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(10);
            rn.oupriority = (r.IsDBNull(11)) ? 0 :  r.GetInt32(11);
            rn.ouflag = r["ouflag"].ToString();
            rn.oupromo = r["oupromo"].ToString();
            rn.dropship = r["dropship"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.stocode = r["stocode"].ToString();
            rn.stoname = r["stoname"].ToString();
            rn.stoaddressln1 = r["stoaddressln1"].ToString();
            rn.stoaddressln2 = r["stoaddressln2"].ToString();
            rn.stoaddressln3 = r["stoaddressln3"].ToString();
            rn.stosubdistict = r["stosubdistict"].ToString();
            rn.stodistrict = r["stodistrict"].ToString();
            rn.stocity = r["stocity"].ToString();
            rn.stocountry = r["stocountry"].ToString();
            rn.stopostcode = r["stopostcode"].ToString();
            rn.stomobile = r["stomobile"].ToString();
            rn.stoemail = r["stoemail"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.inorder = r["inorder"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(33)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(33);
            rn.rowid = (r.IsDBNull(34)) ? 0 :  r.GetInt32(34);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsOutbound o,string fildId){ 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["ouorder"].Value = o.ouorder;
            x.Parameters["outype"].Value = o.outype;
            x.Parameters["ousubtype"].Value = o.ousubtype;
            x.Parameters["thcode"].Value = o.thcode;
            x.Parameters["dateorder"].Value = o.dateorder;
            x.Parameters["dateprep"].Value = o.dateprep;
            x.Parameters["dateexpire"].Value = o.dateexpire;
            x.Parameters["oupriority"].Value = o.oupriority;
            x.Parameters["ouflag"].Value = o.ouflag;
            x.Parameters["oupromo"].Value = o.oupromo;
            x.Parameters["dropship"].Value = o.dropship;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["stocode"].Value = o.stocode;
            x.Parameters["stoname"].Value = o.stoname;
            x.Parameters["stoaddressln1"].Value = o.stoaddressln1;
            x.Parameters["stoaddressln2"].Value = o.stoaddressln2;
            x.Parameters["stoaddressln3"].Value = o.stoaddressln3;
            x.Parameters["stosubdistict"].Value = o.stosubdistict;
            x.Parameters["stodistrict"].Value = o.stodistrict;
            x.Parameters["stocity"].Value = o.stocity;
            x.Parameters["stocountry"].Value = o.stocountry;
            x.Parameters["stopostcode"].Value = o.stopostcode;
            x.Parameters["stomobile"].Value = o.stomobile;
            x.Parameters["stoemail"].Value = o.stoemail;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["inorder"].Value = o.inorder;
            x.Parameters["fileid"].Value = fildId;
            x.Parameters["rowops"].Value = o.rowops;
            x.Parameters["ermsg"].Value = o.ermsg;
            x.Parameters["dateops"].Value = o.dateops;
            x.Parameters["rowid"].Value = o.rowid;
        }
        private SqlCommand getCommand(exsOutbound o,string sqlcmd = "") { 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            //cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.ouorder,"ouorder");
            cm.snapsPar(o.outype,"outype");
            cm.snapsPar(o.ousubtype,"ousubtype");
            cm.snapsPar(o.thcode,"thcode");
            cm.snapsPar(o.dateorder,"dateorder");
            cm.snapsPar(o.dateprep,"dateprep");
            cm.snapsPar(o.dateexpire,"dateexpire");
            cm.snapsPar(o.oupriority,"oupriority");
            cm.snapsPar(o.ouflag,"ouflag");
            cm.snapsPar(o.oupromo,"oupromo");
            cm.snapsPar(o.dropship,"dropship");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.stocode,"stocode");
            cm.snapsPar(o.stoname,"stoname");
            cm.snapsPar(o.stoaddressln1,"stoaddressln1");
            cm.snapsPar(o.stoaddressln2,"stoaddressln2");
            cm.snapsPar(o.stoaddressln3,"stoaddressln3");
            cm.snapsPar(o.stosubdistict,"stosubdistict");
            cm.snapsPar(o.stodistrict,"stodistrict");
            cm.snapsPar(o.stocity,"stocity");
            cm.snapsPar(o.stocountry,"stocountry");
            cm.snapsPar(o.stopostcode,"stopostcode");
            cm.snapsPar(o.stomobile,"stomobile");
            cm.snapsPar(o.stoemail,"stoemail");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.inorder,"inorder");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.rowid,"rowid");
            return cm;
        }

        private exsOutbouln fillOutbouln(ref SqlDataReader r) { 
            exsOutbouln rn = new exsOutbouln();
            rn.orgcode = r["orgcode"].ToString();
            rn.site = r["site"].ToString();
            rn.depot = r["depot"].ToString();
            rn.spcarea = r["spcarea"].ToString();
            rn.ouorder = r["ouorder"].ToString();
            rn.ouln = r["ouln"].ToString();
            rn.ourefno = r["ourefno"].ToString();
            rn.ourefln = r["ourefln"].ToString();
            rn.inorder = r["inorder"].ToString();
            rn.article = r["article"].ToString();
            rn.pv = (r.IsDBNull(10)) ? 0 :  r.GetInt32(10);
            rn.lv = (r.IsDBNull(11)) ? 0 :  r.GetInt32(11);
            rn.unitops = r["unitops"].ToString();
            rn.qtysku = (r.IsDBNull(13)) ? 0 :  r.GetInt32(13);
            rn.qtypu = (r.IsDBNull(14)) ? 0 :  r.GetInt32(14);
            rn.qtyweight =  (r.IsDBNull(15)) ? 0 : r.GetDecimal(15);
            rn.spcselect = r["spcselect"].ToString();
            rn.batchno = r["batchno"].ToString();
            rn.lotno = r["lotno"].ToString();
            rn.datemfg = (r.IsDBNull(19)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(19);
            rn.dateexp = (r.IsDBNull(20)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(20);
            rn.serialno = r["serialno"].ToString();
            rn.orbitsource = r["orbitsource"].ToString();
            rn.tflow = r["tflow"].ToString();
            rn.disthcode = r["disthcode"].ToString();
            rn.fileid = r["fileid"].ToString();
            rn.rowops = r["rowops"].ToString();
            rn.ermsg = r["ermsg"].ToString();
            rn.dateops = (r.IsDBNull(28)) ? (DateTimeOffset?) null : r.GetDateTimeOffset(28);
            rn.rowid = (r.IsDBNull(29)) ? 0 :  r.GetInt32(29);
            rn.ouseq = (r.IsDBNull(30)) ? 0 :  r.GetInt32(30);
            return rn;
        }
        private void fillCommand(ref SqlCommand x, exsOutbouln o,string fildId){ 
            x.Parameters["orgcode"].Value = o.orgcode;
            x.Parameters["site"].Value = o.site;
            x.Parameters["depot"].Value = o.depot;
            //x.Parameters["spcarea"].Value = o.spcarea;
            x.Parameters["ouorder"].Value = o.ouorder;
            x.Parameters["ouln"].Value = o.ouln;
            x.Parameters["ourefno"].Value = o.ourefno;
            x.Parameters["ourefln"].Value = o.ourefln;
            x.Parameters["inorder"].Value = o.inorder;
            x.Parameters["article"].Value = o.article;
            x.Parameters["pv"].Value = o.pv;
            x.Parameters["lv"].Value = o.lv;
            x.Parameters["unitops"].Value = o.unitops;
            x.Parameters["qtysku"].Value = o.qtysku;
            x.Parameters["qtypu"].Value = o.qtypu;
            x.Parameters["qtyweight"].Value = o.qtyweight;
            x.Parameters["spcselect"].Value = o.spcselect;
            x.Parameters["batchno"].Value = o.batchno;
            x.Parameters["lotno"].Value = o.lotno;
            if (o.datemfg.HasValue) { 
                x.Parameters["datemfg"].Value = o.datemfg;
            }else { 
                x.Parameters["datemfg"].Value = DBNull.Value;
            }
            if (o.dateexp.HasValue) { 
                x.Parameters["dateexp"].Value = o.dateexp;
            }else { 
                x.Parameters["dateexp"].Value = DBNull.Value;
            }            
            x.Parameters["serialno"].Value = o.serialno;
            x.Parameters["orbitsource"].Value = o.orbitsource;
            x.Parameters["tflow"].Value = o.tflow;
            x.Parameters["disthcode"].Value = o.disthcode;
            x.Parameters["fileid"].Value = fildId;
            x.Parameters["rowops"].Value = o.rowops;
            x.Parameters["ermsg"].Value = o.ermsg;
            x.Parameters["dateops"].Value = o.dateops;
            x.Parameters["rowid"].Value = o.rowid;
            x.Parameters["ouseq"].Value = o.ouseq;
        }
        private SqlCommand getCommand(exsOutbouln o,string sqlcmd = "") { 
            SqlCommand cm = new SqlCommand(sqlcmd);
            cm.snapsPar(o.orgcode,"orgcode");
            cm.snapsPar(o.site,"site");
            cm.snapsPar(o.depot,"depot");
            //cm.snapsPar(o.spcarea,"spcarea");
            cm.snapsPar(o.ouorder,"ouorder");
            cm.snapsPar(o.ouln,"ouln");
            cm.snapsPar(o.ourefno,"ourefno");
            cm.snapsPar(o.ourefln,"ourefln");
            cm.snapsPar(o.inorder,"inorder");
            cm.snapsPar(o.article,"article");
            cm.snapsPar(o.pv,"pv");
            cm.snapsPar(o.lv,"lv");
            cm.snapsPar(o.unitops,"unitops");
            cm.snapsPar(o.qtysku,"qtysku");
            cm.snapsPar(o.qtypu,"qtypu");
            cm.snapsPar(o.qtyweight,"qtyweight");
            cm.snapsPar(o.spcselect,"spcselect");
            cm.snapsPar(o.batchno,"batchno");
            cm.snapsPar(o.lotno,"lotno");
            cm.snapsPar(o.datemfg,"datemfg");
            cm.snapsPar(o.dateexp,"dateexp");
            cm.snapsPar(o.serialno,"serialno");
            cm.snapsPar(o.orbitsource,"orbitsource");
            cm.snapsPar(o.tflow,"tflow");
            cm.snapsPar(o.disthcode,"disthcode");
            cm.snapsPar(o.fileid,"fileid");
            cm.snapsPar(o.rowops,"rowops");
            cm.snapsPar(o.ermsg,"ermsg");
            cm.snapsPar(o.dateops,"dateops");
            cm.snapsPar(o.rowid,"rowid");
            cm.snapsPar(o.ouseq,"ouseq");
            return cm;
        }
    }
}
